# This is a generated file. Not intended for manual editing.
services:
  geoappapi:
    build:
      context: "/home/emuser/repos/GeoApp"
      dockerfile: "GeoAppAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/GeoAppAPI.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "geoappapi:dev"
    ports: []
    volumes:
    - "/home/emuser/repos/GeoApp/GeoAppAPI:/app:rw"
    - "/home/emuser/repos/GeoApp:/src:rw"
    - "/home/emuser/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
