# This is a generated file. Not intended for manual editing.
services:
  geoappapi:
    build:
      context: "/home/emuser/repos/GeoApp"
      dockerfile: "GeoAppAPI/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57401"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "geoappapi:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57401"
    volumes:
    - "/home/emuser/repos/GeoApp/GeoAppAPI:/app:rw"
    - "/home/emuser/repos/GeoApp:/src:rw"
    - "/home/emuser/.nuget/packages:/home/app/.nuget/packages"
    - "/home/emuser/.local/share/JetBrains/RiderRemoteDebugger/2025.1/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/569/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/emuser/.cache/JetBrains/Rider2025.1/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_4_29_20_39_08:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
